apiVersion: apps/v1
kind: Deployment
metadata:
  name: upravljanje-dogodkov-deployment
  labels:
    app: upravljanje-dogodkov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upravljanje-dogodkov
  template:
    metadata:
      labels:
        app: upravljanje-dogodkov
    spec:
      containers:
        - name: upravljanje-dogodkov
          image: jantopolovec/upravljanje-dogodkov:latest
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3600
            failureThreshold: 3
          #readinessProbe:
          #  httpGet:
          #    path: /health/ready
          #     port: 8080
          #  initialDelaySeconds: 90
          #  periodSeconds: 3600
          #  failureThreshold: 3
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: JWT_SECRET
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: ENVIRONMENT
            - name: FROM_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: FROM_DOMAIN
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: TOKEN
---

apiVersion: v1
kind: Service
metadata:
  name: upravljanje-dogodkov-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: upravljanje-dogodkov