kumuluzee:
  name: upravljanje-dogodkov
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/upravljanje-dogodkov
      connection-url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      pool:
        max-size: 20
  health:
    servlet:
      mapping: /health/
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 3600
    checks:
      data-source-health-check:
        jndi-name: jdbc/upravljanje-dogodkov
      disk-space-health-check:
        threshold: 1000000000
  metrics:
    add-default-tags: false
    servlet:
      enabled: true
      mapping: /metrics

  streaming:
    kafka:
      producer:
        bootstrap-servers: host.docker.internal:9092
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
