kumuluzee:
  name: upravljanje-dogodkov
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/upravljanje-dogodkov
      connection-url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      max-pool-size: 20


