kumuluzee:
  name: upravljanje-dogodkov
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/upravljanje-dogodkov
      connection-url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      pool:
        max-size: 20
  health:
    servlet:
      mapping: /health/
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 3600
    checks:
      data-source-health-check:
        jndi-name: jdbc/upravljanje-dogodkov
      disk-space-health-check:
        threshold: 1000000000


